name: Build and push container image

on:
  workflow_call:
    secrets:
      QUAY_USERNAME:
        description: 'Username for Quay.io'
        required: true
      QUAY_PASSWORD:
        description: 'Password for Quay.io'
        required: true
  push:
    branches:
      - main
      - postprint
    workflow_dispatch:

env:
  # `BASE_URL` determines the website is served from, including CSS & JS assets
  # You may need to change this to `BASE_URL: ''`
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'eds-book'
    steps:
    - name: Checkout files in repo
      uses: actions/checkout@main

    - name: Fetch myst.yml file
      uses: ndelangen/action-read-yaml@1.1.0
      id: read_action_js
      with:
        config: ${{ github.workspace }}/myst.yml

    - name: Build and push the image to quay.io
      uses: jupyterhub/repo2docker-action@master
      with:
        # Make sure username & password/token pair matches your registry credentials
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        DOCKER_REGISTRY: "quay.io"

        # Uncomment and modify the following line with your image name, otherwise no push will happen
        IMAGE_NAME: edsbook/${{ steps.read_action_js.outputs['project.id'] }}

    # Lets us monitor disks getting full as images get bigger over time
    - name: Show how much disk space is left
      run: df -h