name: Execute Notebook

on:
  workflow_call:
  workflow_run:
    workflows: ["Build and push container image"]
    branches: [main, postprint]
    types: [completed]

# This job installs dependencies, build the jupyter notebook, and pushes it to `preview`, a new `branch`
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'eds-book' && github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check conditions meet
        run: echo 'The triggering workflow passed'
      - name: Checkout files in repo
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Fetch myst.yml file
        uses: ndelangen/action-read-yaml@1.1.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/myst.yml
      # Render the notebook
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: quay.io/edsbook/${{ steps.read_action_js.outputs['project.id'] }}:latest
            options: --user root -v ${{ github.workspace }}:/tmp
            shell: bash
            run: |
                v=$(jupyter kernelspec list | awk '{print $1}' | egrep ${{ steps.read_action_js.outputs['project.jupyter.binder.kernelName'] }})
                jupyter-nbconvert --to notebook --ExecutePreprocessor.kernel_name="$v" --inplace --execute ${{ steps.read_action_js.outputs['project.toc.1.file'] }}
                cp ${{ steps.read_action_js.outputs['project.toc.1.file' ]}}  /tmp
      - name: Commit
        run: |
          ls
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ steps.read_action_js.outputs['project.toc.0.file'] }}
          git commit -m 'update'
      - name: Push (render)
        if: github.event.workflow_run.head_branch == 'main'
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: 'render'
         force: true
      - name: Push (preview)
        if: github.event.workflow_run.head_branch == 'postprint'
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: 'preview'
         force: true
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'eds-book' && github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Check conditions meet
        run: echo 'The triggering workflow failed'
